version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - monitoring
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
  grafana:
    depends_on:
      - influxdb
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoring
networks:
  monitoring:
volumes:
  influxdb:
  grafana:
